FROM node:18-alpine as installer

RUN apk add --no-cache git openssh

WORKDIR /app

COPY ./apps/web/package.json .

RUN pnpm install

FROM node:18-alpine as builder

WORKDIR /app

# copy needed files
COPY ./apps/web .

# copy node_modules
COPY --from=installer /app/node_modules ./node_modules

RUN pnpm build 

# cleanup devDependencies
# RUN npm prune --production

# run app
FROM node:18-alpine 

WORKDIR /app

# COPY --from=builder /app .

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder  /app/.next ./.next
COPY --from=builder  /app/.env ./.env
COPY --from=builder  /app/next.config.mjs ./next.config.mjs
COPY --from=builder  /app/package.json ./package.json

CMD pnpm start
