// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	SESSION_PASSWORD: "complex_password_at_least_32_characters_long";
	penx_bucket: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
