// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	SESSION_PASSWORD: "d9321122fba5254adc1302bdb9097f63447170bb199b61dedaf32c710afb81c8";
	BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
