export const langs: Record<string, string> = {
  abap: 'abap',
  // abnf: 'abnf',
  // actionscript: 'actionscript',
  ada: 'ada',
  // agda: 'agda',
  // al: 'al',
  // antlr4: 'antlr4',
  // apacheconf: 'apacheconf',
  apex: 'apex',
  // apl: 'apl',
  applescript: 'applescript',
  // aql: 'aql',
  // arduino: 'arduino',
  // arff: 'arff',
  // armasm: 'armasm',
  // arturo: 'arturo',
  // asciidoc: 'asciidoc',
  // asm6502: 'asm6502',
  // asmatmel: 'asmatmel',
  // aspnet: 'aspnet',
  // autohotkey: 'autohotkey',
  // autoit: 'autoit',
  // avisynth: 'avisynth',
  // 'avro-idl': 'avro-idl',
  // awk: 'awk',
  bash: 'bash',
  basic: 'basic',
  // batch: 'batch',
  // bbcode: 'bbcode',
  // bbj: 'bbj',
  // bicep: 'bicep',
  // birb: 'birb',
  // bison: 'bison',
  bnf: 'bnf',
  // bqn: 'bqn',
  // brainfuck: 'brainfuck',
  // brightscript: 'brightscript',
  // bro: 'bro',
  // bsl: 'bsl',
  c: 'c',
  // cfscript: 'cfscript',
  // chaiscript: 'chaiscript',
  // cil: 'cil',
  // cilkc: 'cilkc',
  // cilkcpp: 'cilkcpp',
  // clike: 'clike',
  clojure: 'clojure',
  cmake: 'cmake',
  cobol: 'cobol',
  coffeescript: 'coffeescript',
  // concurnas: 'concurnas',
  // cooklang: 'cooklang',
  // coq: 'coq',
  // core: 'core',
  cpp: 'cpp',
  // crystal: 'crystal',
  csharp: 'csharp',
  // cshtml: 'cshtml',
  // csp: 'csp',
  // 'css-extras': 'css-extras',
  css: 'css',
  // csv: 'csv',
  // cue: 'cue',
  // cypher: 'cypher',
  // d: 'd',
  dart: 'dart',
  // dataweave: 'dataweave',
  // dax: 'dax',
  // dhall: 'dhall',
  // diff: 'diff',
  // django: 'django',
  // 'dns-zone-file': 'dns-zone-file',
  docker: 'docker',
  // dot: 'dot',
  // ebnf: 'ebnf',
  // editorconfig: 'editorconfig',
  // eiffel: 'eiffel',
  ejs: 'ejs',
  elixir: 'elixir',
  elm: 'elm',
  // erb: 'erb',
  erlang: 'erlang',
  // etlua: 'etlua',
  // 'excel-formula': 'excel-formula',
  // factor: 'factor',
  // false: 'false',
  // 'firestore-security-rules': 'firestore-security-rules',
  flow: 'flow',
  // fortran: 'fortran',
  fsharp: 'fsharp',
  // ftl: 'ftl',
  // gap: 'gap',
  // gcode: 'gcode',
  // gdscript: 'gdscript',
  // gedcom: 'gedcom',
  // gettext: 'gettext',
  // gherkin: 'gherkin',
  // git: 'git',
  // glsl: 'glsl',
  // gml: 'gml',
  // gn: 'gn',
  // 'go-module': 'go-module',
  go: 'go',
  gradle: 'gradle',
  graphql: 'graphql',
  groovy: 'groovy',
  // haml: 'haml',
  handlebars: 'handlebars',
  haskell: 'haskell',
  // haxe: 'haxe',
  // hcl: 'hcl',
  // hlsl: 'hlsl',
  // hoon: 'hoon',
  // hpkp: 'hpkp',
  // hsts: 'hsts',
  html: 'html',
  http: 'http',
  // ichigojam: 'ichigojam',
  // icon: 'icon',
  // 'icu-message-format': 'icu-message-format',
  // idris: 'idris',
  // iecst: 'iecst',
  // ignore: 'ignore',
  // inform7: 'inform7',
  // ini: 'ini',
  // io: 'io',
  // j: 'j',
  java: 'java',
  // javadoc: 'javadoc',
  // javadoclike: 'javadoclike',

  js: 'javascript',
  // javascript: 'javascript',

  // javastacktrace: 'javastacktrace',
  // jexl: 'jexl',
  // jolie: 'jolie',
  // jq: 'jq',
  // 'js-extras': 'js-extras',
  // 'js-templates': 'js-templates',
  // jsdoc: 'jsdoc',
  json: 'json',
  // json5: 'json5',
  // jsonp: 'jsonp',
  // jsstacktrace: 'jsstacktrace',
  jsx: 'jsx',
  julia: 'julia',
  // keepalived: 'keepalived',
  // keyman: 'keyman',
  kotlin: 'kotlin',
  // kumir: 'kumir',
  // kusto: 'kusto',
  latex: 'latex',
  // latte: 'latte',
  less: 'less',
  // lilypond: 'lilypond',
  // 'linker-script': 'linker-script',
  // liquid: 'liquid',
  lisp: 'lisp',
  livescript: 'livescript',
  llvm: 'llvm',
  // log: 'log',
  // lolcode: 'lolcode',
  lua: 'lua',
  // magma: 'magma',
  makefile: 'makefile',
  markdown: 'markdown',
  // 'markup-templating': 'markup-templating',
  markup: 'markup',
  // mata: 'mata',
  matlab: 'matlab',
  // maxscript: 'maxscript',
  // mel: 'mel',
  mermaid: 'mermaid',
  // metafont: 'metafont',
  // mizar: 'mizar',
  // mongodb: 'mongodb',
  // monkey: 'monkey',
  // moonscript: 'moonscript',
  // n1ql: 'n1ql',
  // n4js: 'n4js',
  // 'nand2tetris-hdl': 'nand2tetris-hdl',
  // naniscript: 'naniscript',
  // nasm: 'nasm',
  // neon: 'neon',
  // nevod: 'nevod',
  // nginx: 'nginx',
  // nim: 'nim',
  nix: 'nix',
  // nsis: 'nsis',
  objectivec: 'objectivec',
  ocaml: 'ocaml',
  // odin: 'odin',
  // opencl: 'opencl',
  // openqasm: 'openqasm',
  // oz: 'oz',
  // parigp: 'parigp',
  // parser: 'parser',
  pascal: 'pascal',
  // pascaligo: 'pascaligo',
  // pcaxis: 'pcaxis',
  // peoplecode: 'peoplecode',
  perl: 'perl',
  // 'php-extras': 'php-extras',
  php: 'php',
  // phpdoc: 'phpdoc',
  // 'plant-uml': 'plant-uml',
  // plsql: 'plsql',
  // powerquery: 'powerquery',
  powershell: 'powershell',
  // processing: 'processing',
  prolog: 'prolog',
  // promql: 'promql',
  // properties: 'properties',
  protobuf: 'protobuf',
  // psl: 'psl',
  // pug: 'pug',
  // puppet: 'puppet',
  // pure: 'pure',
  // purebasic: 'purebasic',
  purescript: 'purescript',
  python: 'python',
  // q: 'q',
  // qml: 'qml',
  // qore: 'qore',
  // qsharp: 'qsharp',
  r: 'r',
  // racket: 'racket',
  // reason: 'reason',
  // regex: 'regex',
  // rego: 'rego',
  // renpy: 'renpy',
  // rescript: 'rescript',
  // rest: 'rest',
  // rip: 'rip',
  // roboconf: 'roboconf',
  // robotframework: 'robotframework',
  ruby: 'ruby',
  rust: 'rust',
  // sas: 'sas',
  sass: 'sass',
  scala: 'scala',
  scheme: 'scheme',
  scss: 'scss',
  // 'shell-session': 'shell-session',
  // smali: 'smali',
  // smalltalk: 'smalltalk',
  // smarty: 'smarty',
  // sml: 'sml',
  solidity: 'solidity',
  // 'solution-file': 'solution-file',
  // soy: 'soy',
  // sparql: 'sparql',
  // 'splunk-spl': 'splunk-spl',
  // sqf: 'sqf',
  sql: 'sql',
  // squirrel: 'squirrel',
  // stan: 'stan',
  // stata: 'stata',
  stylus: 'stylus',
  // supercollider: 'supercollider',
  swift: 'swift',
  // systemd: 'systemd',
  // 't4-cs': 't4-cs',
  // 't4-templating': 't4-templating',
  // 't4-vb': 't4-vb',
  // tap: 'tap',
  // tcl: 'tcl',
  // textile: 'textile',
  toml: 'toml',
  // tremor: 'tremor',
  tsx: 'tsx',
  // tt2: 'tt2',
  // turtle: 'turtle',
  // twig: 'twig',
  typescript: 'typescript',
  // typoscript: 'typoscript',
  // unrealscript: 'unrealscript',
  // uorazor: 'uorazor',
  // uri: 'uri',
  // v: 'v',
  // vala: 'vala',
  // vbnet: 'vbnet',
  // velocity: 'velocity',
  // verilog: 'verilog',
  // vhdl: 'vhdl',
  // vim: 'vim',
  // 'visual-basic': 'visual-basic',
  // warpscript: 'warpscript',
  wasm: 'wasm',
  // 'web-idl': 'web-idl',
  // wgsl: 'wgsl',
  // wiki: 'wiki',
  // wolfram: 'wolfram',
  // wren: 'wren',
  // xeora: 'xeora',
  // 'xml-doc': 'xml-doc',
  // xojo: 'xojo',
  // xquery: 'xquery',
  yaml: 'yaml',
  // yang: 'yang',
  zig: 'zig',
}
