export const ELEMENT_TITLE = 'title'
export const ELEMENT_UL = 'unordered-list'
export const ELEMENT_OL = 'ordered-list'
export const ELEMENT_LI = 'list-item'
export const ELEMENT_LIC = 'list-item-text'
